### ISSUE TITLE
[MNT] PyPI and GitHub release sync - `skbase` and `scikit-base`

### ISSUE THREAD

**Issue by yarnabrina** [sktime/skbase#198]
The GitHub release page suggests that latest issue is `0.4.6`, however `PyPI` suggests `0.4.5` as of time of creating this issue. This is most likely caused by failure of [this job](https://github.com/sktime/skbase/actions/runs/5285357416/jobs/9568965104#step:4:28), which seems to be from some access issues.

Since https://github.com/sktime/sktime/issues/4704 suggests use of `0.4.6`, this seems worth fixing by updating the configured secrets.

**Comment by yarnabrina** [comment]
FYI @fkiraly

**Comment by fkiraly** [comment]
@yarnabrina, I see. Well, there is some complication here.
Let me explain the status quo and history.

* pypi `scikit-base` is version 0.4.6 of this repo
* pypi `skbase` is version 0.4.5 of this repo
* `sktime` uses `scikit-base` on pypi, i.e., 0.4.6 of this repo (not 0.4.5 as you think)
* this repo uses Rnkuhns's secrets to push to `skbase`
* but Rnkuhns has removed himself as an admin of `skbase`

Historically:

* we have used the Rnkuhns account secrets to push to `skbase`
* I used to publish `scikit-base` via `twine`, so both `scikit-base` and `skbase` distribute the same package
* around the time where we wanted to rebase `sktime` on `skbase`, Rnkuhns disappeared
* so instead of moving to a dependency on `skbase`, I moved to `scikit-base`, as it was not clear where Rnkuhns was
* Rnkuhns ultimately added me as admin of `skbase` (months after)
* now he has removed himself as pypi admin of `skbase`, which caused the `skbase` 0.4.6 release to fail
* but this is fine for `sktime`, because it actually uses `scikit-base` 0.4.6

Now, going forward, I'm not sure how to resolve all this cleanly for users.
Most users are on `scikit-base`, not `skbase`.

**Comment by fkiraly** [comment]
For the short-term, I can twine-release `skbase` 0.4.5.

For mid-term, I can update this repo's secrets with mine. However, it can point to at most one of `skbase` and `scikit-base`.

**Comment by yarnabrina** [comment]
In my personal experience, difference in package name and import name causes unnecessary confusions. Unless there is a very good reason, for example company policies, brandings, etc., I feel it makes it easier to maintain and use to have same name. The number of time I have seen people confusing between `scikit-learn` and `sklearn` is too high.

Not sure what other developers and community council may think about this, but my personal preference/suggestion will be to continue to use just the shorter form for everything (repository name, package name, import name, PyPI name, conda-forge name) for both `sktime` and `skbase`. 

(Since `sktime` is just `sktime` and not `scikit-time`, I think it also makes sense for consistency point of view. But as `scikit-learn`/`beautifulsoup4` does, may be you can also consider adding a redirect-like functionality as well, which may or may not be a good long term idea.)

**Comment by fkiraly** [comment]
> But as `scikit-learn`/`beautifulsoup4` does, may be you can also consider adding a redirect-like functionality as well

`scikit-learn` has actually *deprecated* the redirect from `sklearn`. So, they only distribute under `scikit-learn`, not `sklearn`!

**Comment by fkiraly** [comment]
Hm, the status quo is that we've been using `scikit-base` as the package name and not pushing releases to `skbase`.

I suppose it is hard to move away from that... any more recent opinions, @yarnabrina?

**Comment by yarnabrina** [comment]
My preference didn't change, but updated opinion about this specific case is same as yours. At the point of creating this issue, I think skbase was just being released and being added in sktime as dependency so rename still would not affect a lot of people, but now it would. So, let's continue with the status quo only.

**Comment by fkiraly** [comment]
yes, apologies for missing this. There are a few circumstances that ended up nudging us into the current status quo, as of 2024, e.g., the naming in the `conda` release etc.

Either way, I'll close the issue then.
