### ISSUE TITLE
BaseObject design reconciliation points

### ISSUE THREAD

**Issue by fkiraly** [sktime/skbase#2]
There are some open points that we need to clarify with the @rnkuhns design. It also needs to work for `sktime`.

Some key points, from an architecture integration perspective:

* @rnkuhns merged the `BaseObject` and the `_HeterogeneousMetaEstimator`. I think this is not a good idea, it merges concerns, and overloads the `BaseObject` with pipeline functionality. I don't think `sktime` can live with that... too many concerns in one place, and refactor of all the pipelines would become a nightmare. I'd really prefer to move away from this god object direction...
* @rnkuhns removed the testing functions, but `sktime` needs those. These should also be public, not private, since other classes interact with them. So from a formal class design perspective, these need to be public unified interface points, even if they are not user facing.
* I like the addition of checking whether the tag containers exist, although instead of raising an error I simply would consider it empty
* `is_composite` is something I added out of a hurry. Perhaps we should sit down and design the components interface more cleanly?

**Comment by RNKuhns** [comment]
@franz, I've got a couple of thoughts related to these:

* ``BaseObject`` (and scikit-learn's ``BaseEstimator`` ) have a ``get_params`` and ``set_params`` interface that already works with certain composites (when parameter values have the parameter getting/setting interface themselves).  ``_HeterogenousMetaEstimator`` adds the parameter getting/setting for another form of composite objects (an iterable of name, object tuples). The composition supported by ``BaseObject`` and ``_HeterogenousMetaEstimator`` both allow for composition of heterogenous objects that use the ``BaseObject`` style interface, just in different forms. By combining those into the same implementation of ``get_params`` and ``set_params`` in ``BaseObject`` we are providing functionality for the range of supported (out-of-the-box) composition in the same place.
* I still want to add the testing interface -- it just needs a slight tweak to work as an external package (it can't rely on a hard-coded location to look for test instance parameters; there are a couple options for generalizing that we need to consider)
* I'm fine with assuming the tag container is empty if it doesn't exist. Maybe we should raise a warning instead of an error (e.g., we noticed you tried to use the tag interface, but don't have _tags or _tags_dynamic attributes. Did you forget to add them to your class?)
*  Agreed on ``is_composite``. I also think it depends on what we determine for the parameter getting/setting. For example, if ``BaseObject`` only supports getting/setting params for "direct" composites (parameter value has the interface), then ``is_composite`` should determine it is a composite object if that case is found. If ``BaseObject`` more broadly supports composite parameter gettting/setting then ``is_composite`` should indicate the object is a composite more broadly.

**Comment by fkiraly** [comment]
Re merging `BaseObject` and `_HeterogeneousMetaEstimator`

>By combining those into the same implementation of ``get_params`` and ``set_params`` in ``BaseObject`` we are providing functionality for the range of supported (out-of-the-box) composition in the same place.

I see this. I think there is a stronger counterargument, in that we are merging too much the generic and the specific. I would separate `BaseObject` having the functionality which *every* object needs, and having functionality which only *some* objects need in another class. `BaseObject` is already heavy enough imo.

Re testing interface: ok, agreed.

Re tag container: ok, agreed with assuming it is empty if does not exist. I would also not raise a warning, I think it should be consistent with attribute inheritance which also does not raise a warning if one of the inheriting classes doesn't have it.

Re `is_composite`: well, then, according to your opinion, it's not too bad in its current state?
